sudo: required
dist: trusty
language: go
before_script:
- sudo ./tools/travis-ci/riak-install
- sudo ./tools/devrel/riak-cluster-config "$(which riak-admin)" 8098 false false
env:
  global:
  - RIAK_HOST=localhost
  - RIAK_PORT=8087
notifications:
  slack:
    secure: czHGTocw0ERiYsnE+CsW6FRs0PM1YU7fleorn5QGxi4gAjbvk+PVEr4YgiJutzJWs+AMCRn8MdIHRTLUcCVewmXDKeLUBRf4Nj8pSgEsOqEHK+ftE35Gy5jNBqGCMr90YF5rSaNCkBFnlW+cy45Z2fvVoy/YkKjlQ2u7A0B1fvZVCHCRT7R3rKkaTApMEp/2gKxKL+7tcITTd0Jh1YdMurhEIo/CXspv57fcerCiRI4vdVj9iup/ZcbvdW4wx5557alvvj4uYntLbsj94cY6ox5t/EEehy8HOBn7pDUAwAbfadQ574EhZMHK0EZMnS3KHMHKf7/xP5inMfplNbIqqMMQ4yHH1vj49l2WdmVOJPWPJs5y9XNV5q9LDkJnp+ZgVLSYBLgzSnzCjJny/p5HH5lUAuaEzOPrif6rOD7zO0swWZDim5kQv5MKC5HK/7BJeLbT7hFHFTZ6gmzB4DFBSiSCfIYRdCrxylJnwiRT5yATKZfVQDBbFs9bwgeDNW3wXLtpZy+0Lx/q1fWi2Z0ZyuvQzOYSt0fLUXMoJILWmXSpWVSFpW4f6tl8kmEStPPPs5DnNOLlc8haZiaIfX9vpeYWBMMZBTl0Gs/ddCbzROTvvInJjkR1liJXmpKtzDYSCafy5ZUYPxSyg8s/mQVAhm+7FMZ/KC6f9gxonaw8oM0=
